name: Build Lambda (ARM64 + Vendored OpenSSL)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install cross-compile toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu build-essential pkg-config

      - name: Add ARM64 Rust target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install cargo-lambda
        run: |
          python3 -m pip install --upgrade pip
          pip install cargo-lambda

      - name: Configure Cargo linker
        run: |
          mkdir -p .cargo
          cat <<EOF > .cargo/config.toml
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Build Lambda with vendored OpenSSL
        env:
          OPENSSL_STATIC: true
        run: cargo lambda build --release --arm64

      - name: Upload Lambda artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-arm64
          path: target/aarch64-unknown-linux-gnu/release/bootstrap





