name: deploy-gcwm-report-gen-lambda
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Zig toolchain
        uses: korandoru/setup-zig@v1
        with:
          # Note: make sure you are using a recent version of zig (the one below isn't kept in sync with new releases)
          zig-version: 0.13.0
      - name: Install Cargo Lambda
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: cargo-lambda/cargo-lambda
          # Note: make sure you are using a recent version of cargo-lambda (the one below isn't kept in sync with new releases)
          tag: v1.6.1 # Remove this if you want to grab always the latest version
          platform: linux # Other valid options: 'windows' or 'darwin'
          arch: x86_64 # Other valid options for linux: 'aarch64'

      - name: Build Lambda
        run: cargo lambda build --release --arm64

      - name: Deploy Lambda
        run: |
          cargo lambda deploy --iam-role arn:aws:iam::691119010791:role/lambda_basic_execution_role
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          
