name: deploy-gcwm-report-gen-lambda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v3

      # 2) Add ARM64 architecture and install cross‐compile OpenSSL dev packages
      - name: Add arm64 architecture & install cross-OpenSSL dev packages
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            libc6-dev:arm64 \
            libssl-dev:arm64 \
            pkg-config-aarch64-linux-gnu
        env:
          PKG_CONFIG_ALLOW_CROSS: "1"
          PKG_CONFIG_SYSROOT_DIR: "/usr/aarch64-linux-gnu"
          PKG_CONFIG_PATH: "/usr/aarch64-linux-gnu/lib/pkgconfig"

      # 3) Build & deploy to Lambda using the Rust action
      - name: Deploy code to Lambda
        uses: qxf2/rust-lambda-action@v1.0.1
        with:
          lambda_directory: '.'
          iam_role: ${{ secrets.AWS_IAM_ROLE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
