# .github/workflows/build-lambda.yml
name: Build Lambda (ARM64 + Vendored OpenSSL)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install cross‐compile toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            build-essential \
            pkg-config

      - name: Add ARM64 Rust target
        run: rustup target add aarch64-unknown-linux-gnu

      - name: Install cargo-lambda
        run: |
          python3 -m pip install --upgrade pip
          pip install cargo-lambda

      - name: Configure Cargo cross‐linker
        run: |
          mkdir -p .cargo
          cat > .cargo/config.toml <<EOF
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Build Lambda with vendored OpenSSL
        run: cargo lambda build --release --arm64
        env:
          # Force openssl-sys to compile its bundled copy
          OPENSSL_STATIC: true

      - name: Upload ARM64 bootstrap artifact
        uses: actions/upload-artifact@v3
        with:
          name: lambda-arm64
          path: |
            target/aarch64-unknown-linux-gnu/release/bootstrap



