name: deploy-gcwm-report-gen-lambda
on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest
    steps: 
      - name:  Install python and cargo lambda
      - uses: actions/setup-python@v5
        run: |
          python -m pip install --upgrade pip
          pip install cargo-lambda

      - name: Install rustup and rust
        uses: MatteoH2O1999/setup-rust@v1

      - uses: actions/checkout@v4
      - name: Build lambda
        run: |
          cargo lambda build --release --arm64

      - name: Deploy lambda
        run: |
          cargo lambda deploy --iam-role ${{ secrets.AWS_IAM_ROLE }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
